#! /bin/sh

NDK_ROOT=/mnt/500G/public/NDK/android-ndk-r16b
SYSROOT=${NDK_ROOT}/platforms/android-27/arch-arm
TOOLCHAIN=${NDK_ROOT}/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64

MYCC="${NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain ${TOOLCHAIN}"

MYCPPFLAGS="-I${NDK_ROOT}/sysroot/usr/include -I${NDK_ROOT}/sysroot/usr/include/arm-linux-androideabi"

MYCFLAGS="-fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -g -target armv7-none-linux-androideabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-exceptions -fno-rtti -marm -O2 -DNDEBUG  -mfpu=neon   -DANDROID -Wa,--noexecstack -Wformat -Werror=format-security -fpie -fexceptions --sysroot ${SYSROOT}"

MYLDFLAGS="-Wl,--gc-sections -Wl,-z,nocopyreloc --sysroot=${SYSROOT} -Wl,-rpath-link=${SYSROOT}/usr/lib -no-canonical-prefixes -target armv7-none-linux-androideabi -Wl,--fix-cortex-a8 -Wl,--build-id -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings -fpie -pie"


CC=${MYCC} CPPFLAGS=${MYCPPFLAGS} CFLAGS=${MYCFLAGS} LDFLAGS=${MYLDFLAGS} ./configure --host=arm-linux-androideabi --enable-shared=false --with-sysroot=${SYSROOT}
